openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of students app
tags:
  - name: Students
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000/api-docs
  - url: https://example.com/api/v1
paths:
  /water/{id}:
    get:
      $ref: "../swagger/paths/water/{id}/get.yaml"
  /water:
    get:
      $ref: "../swagger/paths/water/get.yaml"
    post:
      $ref: "../swagger/paths/water/post.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
